// Standard 7.99
// Priority 15.20
// Next Day 34.99
const orderData = [
  {
    name: "Oversized Jacket/blue",
    price: 284.99,
    size: "small",
    address: "3425 Arlington Street, Brokton, Oklahoma",
    order_number: "2345",
    order_status: true,
    category_name: "Tops",
    updatedAt: "03/10/2022",
    shipping_id: 3,
    user_id: 2,
  },
  {
    name: "Undersized Hoodie",
    price: 154.99,
    size: "small",
    address: "9119 Bingleton Avenue, Ringo, Nevada",
    order_number: "6543",
    order_status: false,
    category_name: "Tops",
    updatedAt: "03/10/2022",
    shipping_id: 3,
    user_id: 2,
  },
  {
    name: "Oversized Jacket/blue",
    price: 265.2,
    size: "large",
    address: "8291 Riverbed Street, Jacksonville, Kentucky",
    order_number: "1350",
    order_status: true,
    category_name: "Tops",
    updatedAt: "03/20/2022",
    shipping_id: 2,
    user_id: 1,
  },
  {
    name: "Levi Pants",
    price: 107.99,
    size: "large",
    address: "8291 Riverbed Street, Jacksonville, California",
    order_number: "1902",
    order_status: false,
    category_name: "Bottoms",
    updatedAt: "03/20/2022",
    shipping_id: 1,
    user_id: 3,
  },
  {
    name: "Undersized Hoodie",
    price: 127.99,
    size: "Extra Large",
    address: "2020 Blackhead Drive, Crimsville, Washington",
    order_number: "1101",
    order_status: false,
    category_name: "Tops",
    updatedAt: "03/22/2022",
    shipping_id: 1,
    user_id: 4,
  },
  {
    name: "Levi Pants/Longsleeve Cardigan",
    price: 162.99,
    size: "Extra Large/Large",
    address: "2020 Blackhead Drive, Crimsville, Washington",
    order_number: "1202",
    order_status: false,
    category_name: "Multiple",
    updatedAt: "03/30/2022",
    shipping_id: 1,
    user_id: 4,
  },
  // Standard 7.99
  // Priority 15.20
  // Next Day 34.99
  {
    name: "Undersized Hoodie",
    price: 135.2,
    size: "Medium",
    address: "9021 Crumber Batch, Angelcity, Florida",
    order_number: "1242",
    order_status: false,
    category_name: "Tops",
    updatedAt: "03/29/2022",
    shipping_id: 2,
    user_id: 5,
  },
  {
    name: "Cargo Pants",
    price: 117.99,
    size: "Extra Large",
    address: "3890 Frenchington, Charleston, Texas",
    order_number: "1022",
    order_status: false,
    category_name: "Bottoms",
    updatedAt: "03/25/2022",
    shipping_id: 1,
    user_id: 6,
  },
  {
    name: "Oversized Jacket",
    price: 284.99,
    size: "Large",
    address: "2020 Blackhead Drive, Crimsville, Washington",
    order_number: "1832",
    order_status: false,
    category_name: "Tops",
    updatedAt: "03/28/2022",
    shipping_id: 1,
    user_id: 7,
  },
];

module.exports = { orderData };
